/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VeterinariosRouteImport } from './routes/veterinarios'
import { Route as TerminosRouteImport } from './routes/terminos'
import { Route as PrivacidadRouteImport } from './routes/privacidad'
import { Route as GraciasRouteImport } from './routes/gracias'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ClinicsRouteImport } from './routes/clinics'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as DashboardVetRouteImport } from './routes/dashboard.vet'
import { Route as DashboardClinicRouteImport } from './routes/dashboard.clinic'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const VeterinariosRoute = VeterinariosRouteImport.update({
  id: '/veterinarios',
  path: '/veterinarios',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminosRoute = TerminosRouteImport.update({
  id: '/terminos',
  path: '/terminos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const GraciasRoute = GraciasRouteImport.update({
  id: '/gracias',
  path: '/gracias',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicsRoute = ClinicsRouteImport.update({
  id: '/clinics',
  path: '/clinics',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardVetRoute = DashboardVetRouteImport.update({
  id: '/dashboard/vet',
  path: '/dashboard/vet',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardClinicRoute = DashboardClinicRouteImport.update({
  id: '/dashboard/clinic',
  path: '/dashboard/clinic',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/clinics': typeof ClinicsRoute
  '/contact': typeof ContactRoute
  '/gracias': typeof GraciasRoute
  '/privacidad': typeof PrivacidadRoute
  '/terminos': typeof TerminosRoute
  '/veterinarios': typeof VeterinariosRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/dashboard/clinic': typeof DashboardClinicRoute
  '/dashboard/vet': typeof DashboardVetRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/clinics': typeof ClinicsRoute
  '/contact': typeof ContactRoute
  '/gracias': typeof GraciasRoute
  '/privacidad': typeof PrivacidadRoute
  '/terminos': typeof TerminosRoute
  '/veterinarios': typeof VeterinariosRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/dashboard/clinic': typeof DashboardClinicRoute
  '/dashboard/vet': typeof DashboardVetRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/clinics': typeof ClinicsRoute
  '/contact': typeof ContactRoute
  '/gracias': typeof GraciasRoute
  '/privacidad': typeof PrivacidadRoute
  '/terminos': typeof TerminosRoute
  '/veterinarios': typeof VeterinariosRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/dashboard/clinic': typeof DashboardClinicRoute
  '/dashboard/vet': typeof DashboardVetRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/clinics'
    | '/contact'
    | '/gracias'
    | '/privacidad'
    | '/terminos'
    | '/veterinarios'
    | '/blog/$slug'
    | '/dashboard/clinic'
    | '/dashboard/vet'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/clinics'
    | '/contact'
    | '/gracias'
    | '/privacidad'
    | '/terminos'
    | '/veterinarios'
    | '/blog/$slug'
    | '/dashboard/clinic'
    | '/dashboard/vet'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/clinics'
    | '/contact'
    | '/gracias'
    | '/privacidad'
    | '/terminos'
    | '/veterinarios'
    | '/blog/$slug'
    | '/dashboard/clinic'
    | '/dashboard/vet'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ClinicsRoute: typeof ClinicsRoute
  ContactRoute: typeof ContactRoute
  GraciasRoute: typeof GraciasRoute
  PrivacidadRoute: typeof PrivacidadRoute
  TerminosRoute: typeof TerminosRoute
  VeterinariosRoute: typeof VeterinariosRoute
  BlogSlugRoute: typeof BlogSlugRoute
  DashboardClinicRoute: typeof DashboardClinicRoute
  DashboardVetRoute: typeof DashboardVetRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/veterinarios': {
      id: '/veterinarios'
      path: '/veterinarios'
      fullPath: '/veterinarios'
      preLoaderRoute: typeof VeterinariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminos': {
      id: '/terminos'
      path: '/terminos'
      fullPath: '/terminos'
      preLoaderRoute: typeof TerminosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gracias': {
      id: '/gracias'
      path: '/gracias'
      fullPath: '/gracias'
      preLoaderRoute: typeof GraciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinics': {
      id: '/clinics'
      path: '/clinics'
      fullPath: '/clinics'
      preLoaderRoute: typeof ClinicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/vet': {
      id: '/dashboard/vet'
      path: '/dashboard/vet'
      fullPath: '/dashboard/vet'
      preLoaderRoute: typeof DashboardVetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/clinic': {
      id: '/dashboard/clinic'
      path: '/dashboard/clinic'
      fullPath: '/dashboard/clinic'
      preLoaderRoute: typeof DashboardClinicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ClinicsRoute: ClinicsRoute,
  ContactRoute: ContactRoute,
  GraciasRoute: GraciasRoute,
  PrivacidadRoute: PrivacidadRoute,
  TerminosRoute: TerminosRoute,
  VeterinariosRoute: VeterinariosRoute,
  BlogSlugRoute: BlogSlugRoute,
  DashboardClinicRoute: DashboardClinicRoute,
  DashboardVetRoute: DashboardVetRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
